name: macos-12 - Clang 13

on:
  push:
    branches: [ master, develop, boost_review_changes ]
  pull_request:
    branches: [ master, develop, boost_review_changes ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

# See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
jobs:
  build:
    strategy:
      matrix:
        cxx_std: [17]

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
  
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DBUILD_WITHOUT_HANA=true -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCXX_STD=${{matrix.cxx_std}}
  
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make -j2
  
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: make check
